config/routes.rb
Politwoops::Application.routes.draw do

  root :to => "tweets#index"

  get "index(.:format)" => "tweets#index", :as => :index
  get "tweet/:id" => "tweets#show", :as => :tweet
  get "tweet/:tweet_id/thumb/:basename.:format" => "tweets#thumbnail"
  get "user/:user_name" => "politicians#show", :as => :politician
  get "users/" => "politicians#all", :as => :all_politicians
  get "party/:name" => "parties#show", :as => :party

  namespace :admin do
    get "status" => "system#status"
    get "restart" => "system#restart"
    get "report" => "system#report"

    get "review" => "tweets#index", :reviewed => false, :approved => false, :as => "review"
    get "unapproved" => "tweets#index", :reviewed => true, :approved => false, :as => "unapproved"
    get "approved" => "tweets#index", :reviewed => true, :approved => true, :as => "approved"

    get "users" => "politicians#admin_list", :as => "admin_list"
    get "user/:id" => "politicians#admin_user", :as => "admin_user"
    post "user/:id/save" => "politicians#save_user", :as => "save_user"
    get "users/new" => "politicians#new_user", :as => "new_user"
    get "users/get-twitter-id/:screen_name" => "politicians#get_twitter_id", :as => "get_twitter_id"

    get "offices" => "offices#list", :as => "list_offices"
    get "offices/add" => "offices#add", :as => "add_office"
    post "offices/save" => "offices#save", :as => "save_office"

    get "offices/:id" => "offices#edit", :as => "edit_office"
    get "review/:rss_secret.rss" => "tweets#index", :reviewed => false, :approved => false, :as => "review_rss", :format => "rss"

    post "review/:id" => "tweets#review", :via => [:post], :as => "review_tweet"

    get "reports/annual/:year" => "reports#annual", :as => "annual_report_year"
    get "reports/annual" => "reports#annual", :as => "annual_report"
    root :to => "tweets#index"
  end

  get "5xx", :to => "errors#down"
  get "404", :to => "errors#not_found"
  get "*anything", :to => "errors#not_found"

end

app/models/tweet.rb
# encoding: utf-8
class Tweet < ActiveRecord::Base
  belongs_to :politician

  has_many :tweet_images, :foreign_key => "tweet_id"

  scope :with_content, -> { where.not content: nil}
  scope :retweets, -> { where.not retweeted_id: nil}

  before_save :extract_retweet_fields

  cattr_reader :per_page
  @@per_page = 10

  def self.in_order
    includes(:politician).order('modified DESC')
  end

  def self.latest
    order('created DESC')
  end

  def self.deleted
    where(deleted: 1).where.not(content: nil)
  end

  def self.in_year(year)
    where("created >= #{Date.new(year, 1, 1)}").where("created <= #{Date.new(year, 12, 31)}")
  end

  def self.random
    Tweet.find(Tweet.pluck(:id).shuffle.first)
  end

  def details
    JSON.parse(tweet)
  end

  def extract_retweeted_status
    return nil if tweet.nil?
    orig_obj = JSON::parse(tweet) rescue nil
    return nil if orig_obj.nil?
    return nil if not orig_obj.is_a?(Hash)
    return nil if orig_obj["retweeted_status"].nil?

    return orig_obj["retweeted_status"]
  end

  def extract_retweet_fields (options = {})
    if retweeted_id.nil? || !options[:overwrite].nil?
      orig_hash = extract_retweeted_status
      if orig_hash
        self.retweeted_id = orig_hash["id"]
        self.retweeted_content = orig_hash["text"]
        self.retweeted_user_name = orig_hash["user"]["screen_name"]
      end
    end
  end

  def twitter_url
    "https://www.twitter.com/#{user_name}/status/#{id}"
  end

  def format
    {
      :created_at => created,
      :updated_at => modified,
      :id => (id and id.to_s),
      :politician_id => politician_id,
      :details => details,
      :content => content,
      :user_name => user_name
    }
  end
end

app/controllers/admin/tweets_controller.rb
class Admin::TweetsController < Admin::AdminController
  before_filter :load_tweet, :only => [:review, :message, :is_hit, :id_tweet]

  # list either unreviewed
  def index
    @page = [params[:page].to_i, 1].max
    @politicians = Politician.active.all

    @tweets = DeletedTweet.in_order.where(:politician_id => @politicians)

    # filter to relevant subset of deleted tweets
    @tweets = @tweets.where :reviewed => params[:reviewed], :approved => params[:approved]

    # show unreviewed tweets oldest to newest
    if !params[:reviewed]
      @tweets = @tweets.reorder "modified ASC"
    end

    @per_page_options = [20, 50]
    @per_page = closest_value((params.fetch :per_page, 0).to_i, @per_page_options)

    @tweets = @tweets.includes(:politician => [:party]).paginate(:page => @page, :per_page => @per_page)
    @admin = true

    respond_to do |format|
      format.html # admin/tweets/index.html.erb
      format.rss do
        response.headers["Content-Type"] = "application/rss+xml; charset=utf-8"
        render "tweets/index"
      end
    end

  end


  # approve or unapprove a tweet, mark it as reviewed either way
  def review
    review_message = (params[:review_message] || "").strip

    if ["Aprobar", "Desaprobar"].include?(params[:commit])
      approved = (params[:commit] == "Aprobar")

      if !@tweet.reviewed? and approved and review_message.blank?
        flash[@tweet.id] = "No olvides incluir una nota con el porque apruebas el tweet."
        redirect_to params[:return_to]
        return false
      end

      @tweet.approved = approved
      @tweet.reviewed = true
      @tweet.reviewed_at = Time.now
    end

    if not review_message.blank?
      @tweet.review_message = review_message
    end

    @tweet.save!
    expire_action :controller => '/tweets', :action => :index

    redirect_to params[:return_to]
  end

  def is_hit
    @tweet.is_hit = params[:is_hit]
    if @tweet.save
      render json: {result: 'tweet save'}
    else
      render json: {result: @tweet.errors}
    end
  end

  # filters

  def load_tweet
    unless params[:id] and (@tweet = DeletedTweet.find(params[:id]))
      render :nothing => true, :status => :not_found
      return false
    end
  end

end

app/controllers/tweets_controller.rb
# encoding: utf-8
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.xml

  require 'RMagick'
  include ApplicationHelper

  caches_action :index,
    :expires_in => 30.minutes,
    :if => proc { (params.keys - ['format', 'action', 'controller']).empty? }

  caches_action :thumbnail

  before_filter :enable_filter_form

  def index
    @filter_action = "/"

    if params.has_key?(:see) && params[:see] == :all
      @tweets = Tweet.in_order
    else
      @tweets = DeletedTweet.in_order
    end

    @tweets = @tweets.where(:politician_id => @politicians)
    tweet_count = 0 #@tweets.count

    if params.has_key?(:q) and params[:q].present?
      # Rails prevents injection attacks by escaping things passed in with ?
      @query = params[:q]
      query = "%#{@query}%"
      @search_pols = Politician.where("MATCH(user_name, first_name, middle_name, last_name) AGAINST (?)", query)
      @tweets = @tweets.where("content like ? or deleted_tweets.user_name like ? or politician_id in (?)", query, query, @search_pols)

    end

    # only approved tweets
    @tweets = @tweets.where(:approved => true)

    @per_page_options = [20, 50]
    @per_page = closest_value((params.fetch :per_page, 0).to_i, @per_page_options)
    @page = [params[:page].to_i, 1].max

    @tweets = @tweets.includes(:tweet_images, :politician => [:party]).paginate(:page => params[:page], :per_page => @per_page)

    respond_to do |format|
      format.html # index.html.erb
      format.rss  do
        response.headers["Content-Type"] = "application/rss+xml; charset=utf-8"
        render
      end
      format.json { render :json => {:meta => {:count => tweet_count}, :tweets => @tweets.map{|tweet| tweet.format } } }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.xml
  def show
    @tweet = DeletedTweet.includes(:politician).find(params[:id])

    if (@tweet.politician.status != 1 and @tweet.politician.status != 4) or not @tweet.approved
      not_found
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tweet }
      format.json  { render :json => @tweet.format }
    end
  end

  def thumbnail
    tweet = Tweet.find(params[:tweet_id])
    if not tweet
      not_found
    end

    images = tweet.tweet_images.all
    if not images
      not_found
    end

    filename = "#{params[:basename]}.#{params[:format]}"
    image = images.select do |img|
      img.filename == filename
    end .first

    if not image
      not_found
    end

    resp = HTTParty.get(image.url)
    img = Magick::Image.from_blob(resp.body)
    layer0 = img[0]
    aspect_ratio = layer0.columns.to_f / layer0.rows.to_f
    if aspect_ratio > 1.0
      new_width = 150
      new_height = layer0.rows.to_f / aspect_ratio
    else
      new_width = layer0.columns.to_f / aspect_ratio
      new_height = 150
    end
    thumb = layer0.resize_to_fit(new_width, new_height)
    send_data(thumb.to_blob,
              :disposition => 'inline',
              :type => resp.headers.fetch('content-type', 'application/octet-stream'),
              :filename => filename)
  end

end

app/helpers/tweets_helper.rb
# encoding: utf-8
module TweetsHelper
  def default_avatar_url (pol)
    if pol.female?
      "/images/avatar_missing_female.png"
    else
      "/images/avatar_missing_male.png"
    end
  end

  def office_title_for (pol)
    pol.office.nil? ? '' : pol.office.title
  end

  def office_abbr_for (pol)
    pol.office.nil? ? '' : pol.office.abbreviation
  end

  def party_name_for (pol)
    pol.party.nil? ? '' : pol.party.name.upcase
  end

  def format_user_name(tweet_content)
    tweet_content.gsub(/(@(\w+))/, %Q{<a href="http://twitter.com/\\2" target="_blank">\\1</a>})
  end
  
  def format_hashtag(tweet_content)
    tweet_content.gsub(/(#(\w+))/, %Q{<a href="https://twitter.com/#!/search?q=%23\\2" target="_blank">\\1</a>})
  end

  def format_retweet_prefix (content, user_name)
    "RT @#{user_name}: #{content}"
  end
  
  def format_tweet(tweet)
    if tweet.retweeted_id.nil?
      content = tweet.content
    else
      content = format_retweet_prefix(tweet.retweeted_content,
                                      tweet.retweeted_user_name)
    end
    content = format_hashtag(content)
    content = format_user_name(content)
    content = auto_link(content, :html => { :target => '_blank' })
  end

  def twitter_url (tweet_user_name, tweet_id)
    "http://www.twitter.com/#{tweet_user_name}/status/#{tweet_id}"
  end

  def byline(tweet, html = true)
    if (Time.now - tweet.modified).to_i > (60 * 60 * 24 * 365)
      tweet_time = tweet.modified.strftime("%l:%M %p")
      tweet_date = tweet.modified.strftime("%d %b %y") # 03 Jun 12
      tweet_when = "at <a class=""linkUnderline"" href=""/tweet/#{tweet.id}"">#{tweet_time} on #{tweet_date}</a>"
    elsif (Time.now - tweet.modified).to_i > (60 * 60 * 24)
      tweet_time = tweet.modified.strftime("%l:%M %p")
      tweet_date = tweet.modified.strftime("%d %b") # 03 Jun
      tweet_when = "at <a class=""linkUnderline"" href=""/tweet/#{tweet.id}"">#{tweet_time} on #{tweet_date}</a>"
    else
      since_tweet = time_ago_in_words tweet.modified
      tweet_when = "<a class=""linkUnderline"" href=""/tweet/#{tweet.id}"">#{since_tweet}</a> ago"
    end
    delete_delay = (tweet.modified - tweet.created).to_i
    
    delay = if delete_delay > (60 * 60 * 24 * 7)
      "after #{pluralize(delete_delay / (60 * 60 * 24 * 7), "week")}"
    elsif delete_delay > (60 * 60 * 24)
      "after #{pluralize(delete_delay / (60 * 60 * 24), "day")}"
    elsif delete_delay > (60 * 60)
      "after #{pluralize(delete_delay / (60 * 60), "hour")}"
    elsif delete_delay > 60
      "after #{pluralize(delete_delay / 60, "minute")}"
    elsif delete_delay > 1
      "after #{pluralize delete_delay, "second"}"
    else
      "immediately"
    end

    if tweet.retweeted_id.nil?
      rt_text = ""
    else
      orig_url = twitter_url(tweet.retweeted_user_name, tweet.retweeted_id)
      rt_text = "<a href=""#{orig_url}"">Original tweet by @#{tweet.retweeted_user_name}</a>."
    end

    if html
      source = tweet.details["source"].to_s.html_safe
      byline = "<a href=\"http://twitter.com/#{tweet.politician.user_name}\" class=\"twitter\">#{tweet.details['user']['name']}</a>".html_safe
      byline += t(:byline,
                  :scope => [:politwoops, :tweets],
                  :retweet => rt_text,
                  :when => tweet_when,
                  :what => source,
                  :delay => delay).html_safe
      byline
    else
      t :byline_text, :scope => [:politwoops, :tweets], :when => tweet_when, :delay => delay
    end
  end

  def rss_date(time)
    time.strftime "%a, %d %b %Y %H:%M:%S %z"
  end

end

app/views/tweets/_tweet.html.erb
<div id="tweet-<%= tweet.id %>" class="tweet">
  <a name="<%= tweet.id %>"></a>

  <% if flash[tweet.id] %>
    <div class="admin_error error">
      <%= flash[tweet.id] %>
    </div>
  <% end %>

	<div class="contentLeft">
		<a href="/user/<%= tweet.politician.user_name %>">
      <img src="<%= default_avatar_url(tweet.politician) %>"
           class="politician-avatar"
           data-lateimg-src="<%= tweet.politician.avatar.url %>"
           alt="<%= tweet.politician.user_name %>"
           width="73"
           height="73">
		</a>
		<div class="policount"><!--
			<span>Retweets via <em>Politwoops</em></span>
			<span class="number">007</span>-->
		</div>
	</div>

  <div class="content">
    <div class="tweet-content">
      <h4 class="tweetTitle">
        <a href="/user/<%= tweet.politician.user_name %>"><%= tweet.details['user']['name'] %> (<%= tweet.politician.party.name.upcase %>)</a>
  	    <span><a class="accountHandle linkUnderline" href="/user/<%= tweet.politician.user_name %>">@<%= tweet.politician.user_name %></a></span>
	    </h4>
	    <% if tweet.politician.status ==  4 %>
            <div class="inactiveMess">Politwoops no longer follows this account.</div>
        <% end %>

      <%= format_tweet(tweet).to_s.html_safe %>
    </div>

    <div class="byline">
      <%= byline tweet %>
    </div>

    <div class="images">
      <% if tweet.tweet_images.any? %>
        <h3>Screenshots of links in this tweet</h3>
        <% tweet.tweet_images.each do |image| %>
          <a href="<%= image.url %>" target="_blank" class="screenshot cboxElement">
              <img src="<%= url_for(:controller => '/tweets',
                                    :action => 'thumbnail',
                                    :tweet_id => tweet.id,
                                    :basename => image.basename,
                                    :format => image.extension) %>" class="screenshot" />
          </a>
        <% end %>
      <% end %>
    </div>


  </div>

  <% if !(defined?(admin) and admin) %>
    <div class="actions">
      <a href="http://twitter.com/share?text=<%= CGI.escape('@' + tweet.user_name + ' ') %>&url=https://projects.propublica.org/politwoops/tweet/<%= tweet.id %>&via=SunFoundation" class="reply textReplace" target="_blank"><%=t :reply, :scope => [:politwoops, :tweets] %></a>
      <a href="http://twitter.com/share?text=<%= CGI.escape('DT @' + tweet.user_name + ' ' + CGI.unescapeHTML(tweet.content)) %>&url=https://projects.propublica.org/politwoops/tweet/<%= tweet.id %>" class="retweet textReplace" target="_blank"><%=t :retweet, :scope => [:politwoops, :tweets] %></a>
    </div>
  <% end %>

  <div class="clear"></div>

  <% if defined?(admin) and admin %>
    <div class="admin review" data-id="<%= tweet.id %>">
      <%= form_tag admin_review_tweet_path(tweet) do %>
        <%= hidden_field_tag "return_to", "#{request.url}##{tweet.id}" %>

        <% if tweet.reviewed? %>
          <div class="review_controls">
            <% if tweet.approved? %>
              <%= submit_tag "Unapprove" %>
            <% else %>
              <%= submit_tag "Approve" %>
            <% end %>

            <% if tweet.reviewed_at %>
              <span class="reviewed_at">
                Reviewed on <%= tweet.reviewed_at.strftime "%B %d, %Y at %I:%M %p" %>:
              </span>
            <% end %>

            <div class="review_message">
              <% if tweet.review_message.present? %>
                <%= light_format tweet.review_message %>
              <% else %>
                (No message entered.)
              <% end %>
            </div>
            <a class="edit" href="#">Edit message</a>
          </div>

          <div class="edit_controls" style="display: none">
            <textarea name="review_message" class="review_message edit"><%= tweet.review_message %></textarea>
            <%= submit_tag "Update" %>
            <a class="cancel" href="#">Cancel</a>
          </div>

        <% else %>
          <%= submit_tag "Unapprove" %>
          <%= submit_tag "Approve" %>
          <br/>
          <label class="review_message">
            A note about why (required if approving)
          </label>
          <textarea name="review_message" class="review_message"></textarea>
        <% end %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/tweets/index.html.erb
<h1 class="app-name">Politwoops</h1>
<h2 class="app-dek">Deleted Tweets from Politicians</h2>
<p class="byline">Originally published by <a href="http://sunlightfoundation.com/">The Sunlight Foundation</a>. Updated regularly.</p>

<p class="guff">Politwoops tracks deleted tweets by current politicians, including those in office and candidates. Explore the collection of tweets that they didn't want you to see. If you think we're missing someone, please <a href="mailto:twoops@sunlightfoundation.com">email us</a> with their Name, State, Political Party, Office they hold or are seeking and, of course, Twitter handle.</p>

<div class="inner-search">
  <%= render :template => "shared/filterform" %>
</div>

<% content_for :feeds do %>
  <% if @politician %>
    <%= auto_discovery_link_tag :rss, politician_url(@politician.user_name, :format => :rss) %>
  <% elsif @query %>
    <%= auto_discovery_link_tag :rss, index_url(:format => :rss, :q => @query) %>
  <% else %>
    <%= auto_discovery_link_tag :rss, index_url(:format => :rss) %>
  <% end %>
<% end %>

<% if @tweets.empty? %>
  No results for the filter options you selected.
<% else %>
  <%= render :partial => "tweets/tweet", :collection => @tweets, :object => :tweet %>

  <%= render :template => "shared/pager" %>

  <%= render :template => "shared/screenshotbox" %>
<% end %>

app/views/tweets/shorten_url.json.erb
{
	"url": "<%= @short_url %>"
}

app/views/tweets/show.html.erb
<% content_for :title do %>
    Deleted tweet from <%= @tweet.details['user']['name'] %>
<% end %>

<h1 class="app-name">Politwoops</h1>
<h2 class="app-dek">Deleted Tweets from Politicians</h2>
<p class="byline">Originally published by <a href="http://sunlightfoundation.com/">The Sunlight Foundation</a>. Updated regularly.</p>

<%= render :partial => "tweets/tweet", :locals => {:tweet => @tweet} %>