config/routes.rb
Politwoops::Application.routes.draw do

  root :to => "tweets#index"

  get "index(.:format)" => "tweets#index", :as => :index
  get "tweet/:id" => "tweets#show", :as => :tweet
  get "tweet/:tweet_id/thumb/:basename.:format" => "tweets#thumbnail"
  get "user/:user_name" => "politicians#show", :as => :politician
  get "users/" => "politicians#all", :as => :all_politicians
  get "party/:name" => "parties#show", :as => :party

  namespace :admin do
    get "status" => "system#status"
    get "restart" => "system#restart"
    get "report" => "system#report"

    get "review" => "tweets#index", :reviewed => false, :approved => false, :as => "review"
    get "unapproved" => "tweets#index", :reviewed => true, :approved => false, :as => "unapproved"
    get "approved" => "tweets#index", :reviewed => true, :approved => true, :as => "approved"

    get "users" => "politicians#admin_list", :as => "admin_list"
    get "user/:id" => "politicians#admin_user", :as => "admin_user"
    post "user/:id/save" => "politicians#save_user", :as => "save_user"
    get "users/new" => "politicians#new_user", :as => "new_user"
    get "users/get-twitter-id/:screen_name" => "politicians#get_twitter_id", :as => "get_twitter_id"

    get "offices" => "offices#list", :as => "list_offices"
    get "offices/add" => "offices#add", :as => "add_office"
    post "offices/save" => "offices#save", :as => "save_office"

    get "offices/:id" => "offices#edit", :as => "edit_office"
    get "review/:rss_secret.rss" => "tweets#index", :reviewed => false, :approved => false, :as => "review_rss", :format => "rss"

    post "review/:id" => "tweets#review", :via => [:post], :as => "review_tweet"

    get "reports/annual/:year" => "reports#annual", :as => "annual_report_year"
    get "reports/annual" => "reports#annual", :as => "annual_report"
    root :to => "tweets#index"
  end

  get "5xx", :to => "errors#down"
  get "404", :to => "errors#not_found"
  get "*anything", :to => "errors#not_found"

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController
  layout "admin"

  before_filter :admin_only

  def annual
    earliest_tweet_timestamp = DeletedTweet.minimum(:created)
    if earliest_tweet_timestamp.nil?
      return not_found
    end
    @year = (params[:year] && params[:year].to_i) || Date.today.year
    if earliest_tweet_timestamp.year > @year
      return not_found
    end

    @tweet_tally = Tweet.joins(:politician).in_year(@year).count
    @delete_tally = DeletedTweet.joins(:politician).in_year(@year).count
    @approval_tally = DeletedTweet.joins(:politician).in_year(@year).where(:approved => true).count
    @approval_pct = (@delete_tally.zero? && 0) || (@approval_tally * 100 / @delete_tally)
    @observed_account_tally = Tweet.joins(:politician).in_year(@year).group(:politician_id).order(nil).count.length

    @tweets_per_account = Tweet.joins(:politician).in_year(@year).group(:politician_id).count
    @deletes_per_account = DeletedTweet.joins(:politician).in_year(@year).group(:politician_id).count
    @twoops_per_account = DeletedTweet.joins(:politician).in_year(@year).where(:approved => true).group(:politician_id).count
    @tweeting_account_tally = @tweets_per_account.length
    @deleting_account_tally = @deletes_per_account.length
    @deleting_account_pct = (@observed_account_tally.zero? && 0) || (@deleting_account_tally * 100 / @observed_account_tally)
    @twooping_account_tally = @twoops_per_account.length

    @top_tweeters = @tweets_per_account.sort_by(&:second).last(5).reverse.map{ |pol_id, cnt| [Politician.find(pol_id), cnt] }
    @top_deleters = @deletes_per_account.sort_by(&:second).last(5).reverse.map{ |pol_id, cnt| [Politician.find(pol_id), cnt] }
    @top_twoopers = @twoops_per_account.sort_by(&:second).last(5).reverse.map{ |pol_id, cnt| [Politician.find(pol_id), cnt] }

    @top_twoops_rates = @deletes_per_account.select{ |pol_id, deletes| deletes > 5 }.map{ |pol_id, deletes| [pol_id, deletes.to_f * 100 / @tweets_per_account[pol_id].to_f] }.sort_by(&:second).last(10)
    @top_twoops_rates = @twoops_per_account.select{ |pol_id, deletes| deletes > 5 }.map{ |pol_id, twoops| [pol_id, twoops.to_f * 100 / @tweets_per_account[pol_id].to_f] }.sort_by(&:second).last(10)
    @top_twoopsters = @top_twoops_rates.reverse.map{ |pol_id, pct| [Politician.find(pol_id), pct.round] }

    @tweets_per_party = Tweet.joins(:politician).in_year(@year).group(:party_id).count
    @deletes_per_party = DeletedTweet.joins(:politician).in_year(@year).group(:party_id).count
    @twoops_per_party = DeletedTweet.joins(:politician).in_year(@year).where(:approved => true).group(:party_id).count
    @parties = Party.find(@tweets_per_party.keys)

    @tweeting_accounts_per_party = Tweet.joins(:politician).in_year(@year).group(:party_id).count(:politician_id, :distinct => true)
    @deleting_accounts_per_party = DeletedTweet.joins(:politician).in_year(@year).group(:party_id).count(:politician_id, :distinct => true)
    @twooping_accounts_per_party = DeletedTweet.joins(:politician).in_year(@year).where(:approved => true).group(:party_id).count(:politician_id, :distinct => true)
  end

end

app/views/admin/reports/annual.html.erb
<div id="annual-report">


  <div id="aggregates">
    <p>

    In <%= @year %> we observed <%= number_with_delimiter @tweet_tally %> tweets from
    <%= number_with_delimiter @observed_account_tally %> accounts.

    Of those accounts, <%= number_with_delimiter @deleting_account_tally %> accounts
    deleted <%= number_with_delimiter @delete_tally %> tweets. Politwoops moderators
    approved <%= number_with_delimiter @approval_tally %>
    (<%= number_with_delimiter @approval_pct %>%) twoops from
    <%= number_with_delimiter @twooping_account_tally %> accounts.

    (some deletions could be of tweets from prior years)
    </p>

  </div>

  <div id="top-tweeters">
    <h3>
    Not all accounts tweet with the same tenacity. These are the accounts with the most tweets:
    </h3>

    <% if @top_tweeters %>
      <ol>
        <% @top_tweeters.each do |pol, cnt|  %>
          <li>
          <span class="ranking-figure"><%= number_with_delimiter cnt %></span>
          <span class="twitter-username"><%= link_to("@#{pol.user_name}", politician_path(pol.user_name)) %></span>
          <span class="pol-name"><%= pol.full_name %></span>
          </li>
        <% end %>
      </ol>
    <% else %>
      <p>No tweeters! What is this world coming to?</p>
    <% end %>
  </div>

  <div id="top-deleters">
    <h3>
    Some accounts delete more tweets than others:
    </h3>
    <% if @top_deleters %>
      <ol>
        <% @top_deleters.each do |pol, cnt|  %>
          <li>
          <span class="ranking-figure"><%= number_with_delimiter cnt %></span>
          <span class="twitter-username"><%= link_to("@#{pol.user_name}", politician_path(pol.user_name)) %></span>
          <span class="pol-name"><%= pol.full_name %></span>
          </li>
        <% end %>
      </ol>
    <% else %>
      <p>No tweet deleters! Are we even on earth?</p>
    <% end %>
  </div>


  <div id="top-twoopers">
    <h3>
      Some accounts have more of their deletions <i>approved</i> than others:
    </h3>
    <% if @top_twoopers %>
      <ol>
        <% @top_twoopers.each do |pol, cnt|  %>
          <li>
          <span class="ranking-figure"><%= number_with_delimiter cnt %></span>
          <span class="twitter-username"><%= link_to("@#{pol.user_name}", politician_path(pol.user_name)) %></span>
          <span class="pol-name"><%= pol.full_name %></span>
          </li>
        <% end %>
      </ol>
    <% else %>
      <p>No approved deletes! Momma? Is that you?</p>
    <% end %>
  </div>

  <div id="top-twoopsters">
    <h3>
    These are the accounts whose tweets are most likely to become twoops (with a minimum of 5 twoops):
    </h3>

    <% if @top_twoopsters %>
      <ol>
        <% @top_twoopsters.each do |pol, pct| %>
          <li>
          <span class="ranking-figure"><%= pct %>% (of <%= number_with_delimiter pol.tweets.in_year(@year).count %>)</span>
          <span class="twitter-username"><%= link_to("@#{pol.user_name}", politician_path(pol.user_name)) %></span>
          <span class="pol-name"><%= pol.full_name %></span>
          </li>
        <% end %>
      </ol>
    <% end %>
  </div>

  <div id="party-tweeting">
    <h3>
      How much does each party tweet?
    </h3>
    <% if @tweets_per_party %>
      <table>
        <thead>
          <tr><th>Party</th><th>Accounts</th><th>Tweets</th><th>Deletes</th><th>Twoops</th><th>Mean Twoops</th></tr>
        </thead>
        <tbody>
        <% @parties.each do |party| %>
          <% if @tweets_per_party[party.id] %>
            <tr>
              <td><%= party.display_name %></td>
              <td><%= (number_with_delimiter @tweeting_accounts_per_party[party.id]) || 0 %></td>
              <td><%= (number_with_delimiter @tweets_per_party[party.id]) || 0 %></td>
              <td><%= (number_with_delimiter @deletes_per_party[party.id]) || 0 %></td>
              <td><%= (number_with_delimiter @twoops_per_party[party.id]) || 0 %></td>
              <td><%= number_with_precision (@twoops_per_party[party.id] || 0).to_f / @tweeting_accounts_per_party[party.id].to_f, :precision => 1 %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
      </table>
    <% else %>
      <p>No party data make your twoopserver cry :(</p>
    <% end %>
  </div>

  <ul class="footnotes">
    <li>* Twoops are tweets that are deleted and then approved by moderators.</li>
  </ul>
</div>